STAKEHOLDER_TOP_SQL = """
WITH stakeholders AS (
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0) AS CONTRACT_VALUE_GROSS,
         CONTRACT_STAKEHOLDER_1 AS STAKEHOLDER,
         DEPARTMENT_1 AS DEPARTMENT,
         REQUEST_DATE AS REF_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_2,
         DEPARTMENT_2,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_3,
         DEPARTMENT_3,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_4,
         DEPARTMENT_4,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_5,
         DEPARTMENT_5,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_6,
         DEPARTMENT_6,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_7,
         DEPARTMENT_7,
         REQUEST_DATE
    FROM "Contract"
  UNION ALL
  SELECT CONTRACT_ID,
         NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0),
         CONTRACT_STAKEHOLDER_8,
         DEPARTMENT_8,
         REQUEST_DATE
    FROM "Contract"
)
SELECT
  TRIM(STAKEHOLDER) AS stakeholder,
  SUM(CONTRACT_VALUE_GROSS) AS total_gross_value,
  COUNT(DISTINCT CONTRACT_ID) AS contract_count,
  LISTAGG(DISTINCT TRIM(DEPARTMENT), ', ') WITHIN GROUP (ORDER BY TRIM(DEPARTMENT)) AS departments
FROM stakeholders
WHERE STAKEHOLDER IS NOT NULL
  AND TRIM(STAKEHOLDER) <> ''
  AND (:date_start IS NULL OR REF_DATE >= :date_start)
  AND (:date_end   IS NULL OR REF_DATE <  :date_end)
GROUP BY TRIM(STAKEHOLDER)
ORDER BY total_gross_value DESC
FETCH FIRST :top_n ROWS ONLY
"""

DEPARTMENT_TOP_SQL = """
SELECT
  TRIM(OWNER_DEPARTMENT) AS department,
  SUM(NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0)) AS total_gross_value,
  COUNT(*) AS contract_count
FROM "Contract"
WHERE OWNER_DEPARTMENT IS NOT NULL
  AND TRIM(OWNER_DEPARTMENT) <> ''
  AND (:date_start IS NULL OR REQUEST_DATE >= :date_start)
  AND (:date_end   IS NULL OR REQUEST_DATE <  :date_end)
GROUP BY TRIM(OWNER_DEPARTMENT)
ORDER BY total_gross_value DESC
FETCH FIRST :top_n ROWS ONLY
"""

EXPIRY_IN_NEXT_N_SQL = """
SELECT
  CONTRACT_ID,
  END_DATE,
  CONTRACT_OWNER,
  NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0) AS contract_value_gross,
  CONTRACT_STATUS
FROM "Contract"
WHERE END_DATE >= :date_start
  AND END_DATE  < :date_end
ORDER BY END_DATE ASC
"""

STATUS_BREAKDOWN_SQL = """
SELECT
  TRIM(CONTRACT_STATUS) AS contract_status,
  COUNT(*) AS cnt,
  SUM(NVL(CONTRACT_VALUE_NET_OF_VAT,0) + NVL(VAT,0)) AS total_gross_value
FROM "Contract"
WHERE (:date_start IS NULL OR REQUEST_DATE >= :date_start)
  AND (:date_end   IS NULL OR REQUEST_DATE <  :date_end)
GROUP BY TRIM(CONTRACT_STATUS)
ORDER BY cnt DESC
"""
