"""Column synonym maps for Contract planner helpers."""
from __future__ import annotations

from typing import Dict, List

STAKEHOLDER_COLUMNS: List[str] = [
    "CONTRACT_STAKEHOLDER_1",
    "CONTRACT_STAKEHOLDER_2",
    "CONTRACT_STAKEHOLDER_3",
    "CONTRACT_STAKEHOLDER_4",
    "CONTRACT_STAKEHOLDER_5",
    "CONTRACT_STAKEHOLDER_6",
    "CONTRACT_STAKEHOLDER_7",
    "CONTRACT_STAKEHOLDER_8",
]

COLUMN_SYNONYMS: Dict[str, List[str]] = {
    "DEPARTMENTS": ["OWNER_DEPARTMENT"],
    "DEPARTMENT": ["OWNER_DEPARTMENT"],
    "OWNER DEPARTMENT": ["OWNER_DEPARTMENT"],
    "OWNER_DEPARTMENT": ["OWNER_DEPARTMENT"],
    "DEPARTMENT_OUL": ["DEPARTMENT_OUL"],
    "DEPARTMENT OUL": ["DEPARTMENT_OUL"],
    "STAKEHOLDER": STAKEHOLDER_COLUMNS,
    "STAKEHOLDERS": STAKEHOLDER_COLUMNS,
    "STACKHOLDER": STAKEHOLDER_COLUMNS,
    "STACKHOLDERS": STAKEHOLDER_COLUMNS,
}

__all__ = ["STAKEHOLDER_COLUMNS", "COLUMN_SYNONYMS"]
